databases:
  - name: budgetify
    databaseName: budgetify
    user: budgetify

services:
  - type: web
    name: budgetify
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgetify
          property: connectionString
      - key: QrkL9W/g9wY06ZQIbPHiTBcbTVdQgY0Dy4sJpz0x2Cjk5GZ+2PJC7LZKUTja11FEJby1zchSO1XMJhLwwnn27Fmmb+esNGNSrhx096yjtOX5m0x5JMl0/DFQMpZqG0jYbrLdGKGYuHEgPyCUTlY00g+NER3R/oUTyfcNvvuCIRgGqotIDtmiQPRH1Ks/r3cqutAVQCYR9mBHMgs4DZnI9Eh31hzkslMDwNmwGAHrAzNbtj9WGdplBKJYiKU2kiqgXcQXzp3sNtlzpysqFdYnHo1qiGWAY75/zBEE5bnRF1w2GIA5AQ+RBEoo8+QOdiOuUDm4wp/w+ZXyHvFOc/rND833/TCLa13+K17oualxEoMhznGfRWIs4wgDqg8qu+O0a1ttU3ax4yXG6/H1L9OwVRu0ktpX--sUpBKlueAzoLvIV+--Odsa0LAUZFjwYJYImzyCMA==
        sync: false
